name: Fetch Football Data

on:
  # Manuel çalıştırmaya izin verir
  workflow_dispatch: 
  # Otomatik çalıştırma zamanlaması (UTC saatinde Perşembe 03:00 ve Pazar 03:00)
  schedule:
    - cron: '0 3 * * 4' # Perşembe 03:00 UTC
    - cron: '0 3 * * 0' # Pazar 03:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Commit at adımının çalışması için geçmişi al
        fetch-depth: 0 
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies 
      run: |
        # Sadece BeautifulSoup ve Requests gibi hafif bağımlılıkları kurar.
        # Selenium ve tarayıcı bağımlılıkları artık yoktur.
        pip install requests beautifulsoup4 
        
    - name: Run data fetching script
      run: python fetch_football_data.py
      
    - name: Commit and Push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # 'data/' klasörü altındaki tüm değişiklikleri kontrol et
        file_pattern: data/
        commit_message: "Güncel Futbol Verileri: Otomatik Güncelleme"
        # Değişiklik yoksa push yapmaz
        skip_dirty_check: true 
        # Yeni ve güncel dosyaları commit'e dahil et
        commit_options: '--allow-empty --no-verify'
